version: "3.8"

services:
  db:
    container_name: postgres_container_wild_west
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: testing?
      POSTGRES_USER: testing
      POSTGRES_DB: testing_db
      PGDATA: /var/lib/postgresql/data
    expose:
      - "6543"
    ports:
      - "6543:6543"
    networks:
      - supabaseNetwork
    command: -p 6543 -c wal_level=logical
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container_wild_west
    image: dpage/pgadmin4:6.19
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: db@db.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 6544
    ports:
      - "6544:6544"
    networks:
      - supabaseNetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  supabaseNetwork:
    name: supabase_network_flow
    external: true

volumes:
  db-data:
  pgadmin-data:
